#!/bin/sh
# Moviuro <moviuro+nagios[at]gmail.com>

# check_ipsec -f <from> -t <to>

# requires sudo authorization for the nrpe user on command "ipsecctl -s sa"
# /etc/sudoers
# Cmnd_Alias IPSECSTATUS = /sbin/ipsecctl -s sa
# # replace _nrpe with the actual name of the NRPE user
# _nrpe   ALL=IPSECSTATUS, NOPASSWD: IPSECSTATUS

# [...]/nrpe.cfg
# command[check_ipsec]=/<path>/ginfo-nagios-plugins/client/check_ipsec -f <from> -t <to>

# define service{
#        use                     <template>
#        host_name               <hostname>
#        service_description     IPSEC
#        check_command           check_nrpe!check_ipsec
# }

state_ok=0
#state_warning=1
state_critical=2
#state_unknown=3
#state_dependent=4

while [ $# -gt 1 ]; do
    case $1 in
        -f|-from)
            from="$2"
            ;;
        -t|-to)
            to="$2"
            ;;
    esac
    shift 2
done

if sudo ipsecctl -s sa | grep -q "$from to $to" 2>&1; then
    echo "IPSEC OK - link between $from and $to exists"
    return "$state_ok"
fi

echo "IPSEC CRITICAL - link between $from and $to doesn't exist"
return "$state_critical"
